const productsList = [
  {
    name: 'Green Tea Amino Acid Face Cleanser',
    price: 12,
    source: 'green tea',
    type: 'hydration',
    category: 'cleanser',
    best: true,
    stock: true,
    img: 'img/products/green-tea/cleanser.png',
  },
  {
    name: 'Green Tea Cleansing Oil',
    price: 24,
    source: 'green tea',
    type: 'hydration',
    category: 'cleanser',
    best: false,
    stock: true,
    img: 'img/products/green-tea/cleansing-oil.png',
  },
  {
    name: 'Green Tea Micellar Cleansing Water',
    price: 17,
    source: 'green tea',
    type: 'hydration',
    category: 'cleanser',
    best: false,
    stock: true,
    img: 'img/products/green-tea/cleansing-water.png',
  },
  {
    name: 'Green Tea Balancing Emulsion',
    price: 19,
    source: 'green tea',
    type: 'hydration',
    category: 'moisturizer',
    stock: false,
    img: 'img/products/green-tea/emulsion.png',
  },
  {
    name: 'Green Tea Balancing Cream',
    price: 22,
    source: 'green tea',
    type: 'hydration',
    category: 'moisturizer',
    best: false,
    stock: true,
    img: 'img/products/green-tea/cream00.png',
  },
  {
    name: 'Green Tea Hyaluronic Acid Toner',
    price: 22,
    source: 'green tea',
    type: 'hydration',
    category: 'toner',
    best: true,
    stock: true,
    img: 'img/products/green-tea/toner.png',
  },
  {
    name: 'Green Tea Hyaluronic Acid Serum',
    price: 30,
    source: 'green tea',
    type: 'hydration',
    category: 'serum',
    best: true,
    stock: true,
    img: 'img/products/green-tea/serum.png',
  },
  {
    name: 'Green Tea Caffeine Bright-Eye Serum',
    price: 22,
    source: 'green tea',
    type: 'hydration',
    category: 'eye care',
    best: true,
    stock: true,
    img: 'img/products/green-tea/eye-serum.png',
  },
  {
    name: 'Green Tea Hyaluronic Acid Eye Cream',
    price: 29,
    source: 'green tea',
    type: 'hydration',
    category: 'eye care',
    best: false,
    stock: true,
    img: 'img/products/green-tea/eye-cream.png',
  },
  {
    name: 'Green Tea Hyaluronic Acid Cream',
    price: 29,
    source: 'green tea',
    type: 'hydration',
    category: 'moisturizer',
    best: true,
    stock: true,
    img: 'img/products/green-tea/cream01.png',
  },
  {
    name: 'Pore Clearing Facial Foam',
    price: 14,
    source: 'volcanic clusters',
    type: 'pore solutions',
    category: 'cleanser',
    best: false,
    stock: true,
    img: 'img/products/volcanic-clusters/facial-foam.png',
  },
  {
    name: 'Pore Clearing Cleansing Balm',
    price: 10,
    source: 'volcanic clusters',
    type: 'pore solutions',
    category: 'cleanser',
    best: false,
    stock: false,
    img: 'img/products/volcanic-clusters/cleansing-balm.png',
  },
  {
    name: 'Pore Clearing Toner 2X',
    price: 22,
    source: 'volcanic clusters',
    type: 'pore solutions',
    category: 'toner',
    best: false,
    stock: true,
    img: 'img/products/volcanic-clusters/toner.png',
  },
  {
    name: 'Pore Clearing Clay Peel Off Mask 2X',
    price: 16,
    source: 'volcanic clusters',
    type: 'pore solutions',
    category: 'face masks',
    best: false,
    stock: true,
    img: 'img/products/volcanic-clusters/peel-off-mask.png',
  },
  {
    name: 'Pore Clearing Clay Mask 2X',
    price: 16,
    source: 'volcanic clusters',
    type: 'pore solutions',
    category: 'face masks',
    best: true,
    stock: true,
    img: 'img/products/volcanic-clusters/clay-mask.png',
  },
  {
    name: 'Pore Clearing Clay Mousse Mask 2X',
    price: 24,
    source: 'volcanic clusters',
    type: 'pore solutions',
    category: 'face masks',
    best: false,
    stock: true,
    img: 'img/products/volcanic-clusters/mousse-mask.png',
  },
  {
    name: 'Dewy Glow Jam Cleanser',
    price: 13,
    source: 'cherry blossom',
    type: 'brightening',
    category: 'cleanser',
    best: false,
    stock: true,
    img: 'img/products/cherry-blossom/cleanser.png',
  },
  {
    name: 'Dewy Glow Toner',
    price: 20,
    source: 'cherry blossom',
    type: 'brightening',
    category: 'toner',
    best: false,
    stock: true,
    img: 'img/products/cherry-blossom/toner.png',
  },
  {
    name: 'Dewy Glow Mist',
    price: 22,
    source: 'cherry blossom',
    type: 'brightening',
    category: 'toner',
    best: false,
    stock: true,
    img: 'img/products/cherry-blossom/mist.png',
  },
  {
    name: 'Dewy Glow Emulsion',
    price: 20,
    source: 'cherry blossom',
    type: 'brightening',
    category: 'moisturizer',
    best: false,
    stock: true,
    img: 'img/products/cherry-blossom/emulsion.png',
  },
  {
    name: 'Dewy Glow Jelly Cream',
    price: 26,
    source: 'cherry blossom',
    type: 'brightening',
    category: 'moisturizer',
    best: false,
    stock: true,
    img: 'img/products/cherry-blossom/cream00.png',
  },
  {
    name: 'Dewy Glow Tone-up Cream',
    price: 26,
    source: 'cherry blossom',
    type: 'brightening',
    category: 'moisturizer',
    best: false,
    stock: true,
    img: 'img/products/cherry-blossom/cream01.png',
  },
  {
    name: 'Youth-Enriched Toner',
    price: 24,
    source: 'orchid',
    type: 'anti-aging',
    category: 'toner',
    best: false,
    stock: true,
    img: 'img/products/orchid/toner.png',
  },
  {
    name: 'Youth-Enriched Serum',
    price: 32,
    source: 'orchid',
    type: 'anti-aging',
    category: 'serum',
    best: false,
    stock: true,
    img: 'img/products/orchid/serum.png',
  },
  {
    name: 'Youth-Enriched Emulsion',
    price: 24,
    source: 'orchid',
    type: 'anti-aging',
    category: 'moisturizer',
    best: false,
    stock: true,
    img: 'img/products/orchid/emulsion.png',
  },
  {
    name: 'Youth-Enriched Eye Cream',
    price: 29,
    source: 'orchid',
    type: 'anti-aging',
    category: 'eye care',
    best: true,
    stock: true,
    img: 'img/products/orchid/eye-cream.png',
  },
  {
    name: 'Youth-Enriched Gel Cream',
    price: 29,
    source: 'orchid',
    type: 'anti-aging',
    category: 'moisturizer',
    best: true,
    stock: false,
    img: 'img/products/orchid/cream00.png',
  },
  {
    name: 'Youth-Enriched Cream',
    price: 29,
    source: 'orchid',
    type: 'anti-aging',
    category: 'moisturizer',
    stock: true,
    img: 'img/products/orchid/cream01.png',
  },
  {
    name: 'Youth-Enriched Rich Cream',
    price: 31,
    source: 'orchid',
    type: 'anti-aging',
    category: 'moisturizer',
    best: true,
    stock: true,
    img: 'img/products/orchid/cream02.png',
  },
  {
    name: 'Brightening & Pore-caring Facial Cleanser',
    price: 17,
    source: 'tangerine',
    type: 'brightening',
    category: 'cleanser',
    best: false,
    stock: true,
    img: 'img/products/tangerine/cleanser.png',
  },
  {
    name: 'Brightening & Pore-caring Serum',
    price: 37,
    source: 'tangerine',
    type: 'brightening',
    category: 'serum',
    best: false,
    stock: true,
    img: 'img/products/tangerine/serum.png',
  },
  {
    name: 'Brightening & Pore-caring Cream',
    price: 33,
    source: 'tangerine',
    type: 'brightening',
    category: 'moisturizer',
    best: false,
    stock: true,
    img: 'img/products/tangerine/cream.png',
  },
  {
    name: 'Youth Enhancing Treatment Essence',
    price: 40,
    source: 'black tea',
    type: 'anti-aging',
    category: 'serum',
    best: false,
    stock: true,
    img: 'img/products/black-tea/essence.png',
  },
  {
    name: 'Youth Enhancing Serum',
    price: 39,
    source: 'black tea',
    type: 'anti-aging',
    category: 'serum',
    best: true,
    stock: true,
    img: 'img/products/black-tea/serum.png',
  },
  {
    name: 'Youth Enhancing Cream',
    price: 35,
    source: 'black tea',
    type: 'anti-aging',
    category: 'moisturizer',
    best: false,
    stock: true,
    img: 'img/products/black-tea/cream.png',
  },
  {
    name: 'Clarifying Cleansing Foam',
    price: 12,
    source: 'bija',
    type: 'troubled skin',
    category: 'cleanser',
    best: true,
    stock: true,
    img: 'img/products/bija/cleansing-foam.png',
  },
  {
    name: 'Clarifying Toner',
    price: 19,
    source: 'bija',
    type: 'troubled skin',
    category: 'toner',
    best: false,
    stock: true,
    img: 'img/products/bija/toner.png',
  },
  {
    name: 'Cica Balm',
    price: 25,
    source: 'bija',
    type: 'troubled skin',
    category: 'balm',
    best: false,
    stock: true,
    img: 'img/products/bija/balm.png',
  },
  {
    name: 'Clarifying Spot Serum',
    price: 18,
    source: 'bija',
    type: 'troubled skin',
    category: 'serum',
    best: false,
    stock: false,
    img: 'img/products/bija/serum.png',
  },
  {
    name: 'Clarifying Emulsion',
    price: 19,
    source: 'bija',
    type: 'troubled skin',
    category: 'emulsion',
    best: false,
    stock: true,
    img: 'img/products/bija/emulsion.png',
  },
  {
    name: 'Nourishing Ampoule Toner',
    price: 23,
    source: 'ginger honey',
    type: 'hydration',
    category: 'toner',
    best: false,
    stock: true,
    img: 'img/products/ginger-honey/toner.png',
  },
];

const products = document.querySelector('.products__table');
const filter = document.querySelectorAll('.products__filter--option');
const category = filter[0];
const skinConcerns = filter[1];
const ingredients = filter[2];
const best = productsList.filter((product) => product.best === true);

const productsItem = (item) => {
  for (let i = 0; i < item.length; i++) {
    products.innerHTML += `<div class='products__table--item'>
        <img src=${item[i].img} alt=${item[i].name} class='products__img' />
        <p class='products__title'>${item[i].name}</p>
        <p class='products__price'>$${item[i].price}</p>
        <a class='products__cart ${item[i].stock ? '' : 'out-of-stock'}'>${
      item[i].stock ? 'Add Cart' : 'Out of Stock'
    }</a>
      </div>`;
  }
};

// const header = () => {
//   document.querySelector('products__header > .heading-secondary');
// };

// Default List(Best Products)
productsItem(best);

const productsFilter = (option, type) => {
  const item = option.value;
  const itemInfo = productsList.filter((product) => product[type] === item);

  products.innerHTML = '';

  productsItem(itemInfo);
};

category.addEventListener('change', () => productsFilter(category, 'category'));

skinConcerns.addEventListener('change', () =>
  productsFilter(skinConcerns, 'type')
);

ingredients.addEventListener('change', () =>
  productsFilter(ingredients, 'source')
);
